
	<h2><?php echo $this->translate('Favourite authors');?></h2>
	
	<?php if(isset($this->authors) ):?>
		<ul>
		<?php 
		$count = count($this->authors);
		$i = 1;
		
		foreach($this->authors as $author):
			$name = $author[0]->getFullname();?>
			
			<li <?php echo 'class="' . ($i++ % 2 == 0 ? 'even' : 'odd') . '"';?>>
			<?php 
					$str = ' ('. $author['amount'] . ')';
			
				echo $this->linkTo($name . ": " . $str, 'bookshelf/book/list/author/' . $author[0]->getId());
				?>
			</li>
		<?php endforeach;?>
		</ul>
	<?php endif;?>
