

var authorsFindAction = '<?php echo $this->url(array(
                         'module' => 'bookshelf',
                         'controller' => 'author',
                         'action' => 'find',
                       ), 'default', true); ?>';
                       
var genresFindAction = '<?php echo $this->url(array(
                         'module' => 'bookshelf',
                         'controller' => 'genre',
                         'action' => 'find',
                       ), 'default', true); ?>';
                       
var tagsFindAction = '<?php echo $this->url(array(
                         'module' => 'bookshelf',
                         'controller' => 'tag',
                         'action' => 'find',
                       ), 'default', true); ?>';

var findAction = '<?php echo $this->url(array(
                         'module' => 'bookshelf',
                         'controller' => 'author',
                         'action' => 'find',
                       ), 'default', true); ?>';

var findGenreAction = '<?php echo $this->url(array(
                         'module' => 'bookshelf',
                         'controller' => 'genre',
                         'action' => 'find',
                       ), 'default', true); ?>';
                       
var findTagAction   = '<?php echo $this->url(array(
                         'module' => 'bookshelf',
                         'controller' => 'tag',
                         'action' => 'find',
                       ), 'default', true); ?>';

var addTagAction = '<?php echo $this->url(array(
                         'module' => 'bookshelf',
                         'controller' => 'tag',
                         'action' => 'add',
                       ), 'default', true); ?>';
