<h1>Munkirjat.fi</h1>

<h2>About</h2>

<p>This is a personal virtual bookshelf created for helping me figuring out, whether I own a certain book or not.</p>

<p>I read and buy quite a lot of books and
sometimes it is a bit hard to remember, if I have a certain book already as I might have over 10 books from a certain author.</p>

<p>Currently the layout is very, very spartan but the app does what it needs to.</p>

<h2>Why?</h2>

<p>I could certainly have just produced a simple list of all my books but that's not fun to code, is it. ;)</p>

<p>I wanted to create a web app that I have use for and that is fun to code and helps me to learn new stuff.</p>

<h2>Technology used</h2>

<p>This web app is built using <a href="http://framework.zend.com">Zend Framework (1.11.6 as of writing)</a> and <a href="http://www.doctrine-project.org">Doctrine 2.1.x</a>. I DO NOT use Zend_Db at all.</p>

<p>For AJAX and Javascript, I use <a href="http://www.jquery.com">jQuery</a>.</p>

<p>I chose Zend Framework as the main framework because I simply digg it. It is quite fun to code with and has a great community.</p>

<p>Doctrine is my number one choice when I need to hit the database as it lets me write less tedious and boring SQL.</p>

<p><a href="/">Back</a></p>