<?php echo $this->render('book/partials/init-rating.phtml');?>

<?php if(isset($this->books) ):?>
	<p>Books marked with <span class="is_read">red</span> have not yet been read.</p>
	<table id="data_list">
		<tr>
			<th>#</th>
			<th id="book_title_col"><?php echo $this->translate('Title');?></th>
			<th id="book_rating_col"><?php echo $this->translate('Rating');?></th>
		</tr>
		<?php 
		$i = 1;
		$r = 0;
		$c = 1; 
		$previousAuthor = null;
		
		foreach($this->books as $bookArr):
			
		    $book = $bookArr[0];
		    $amount = $bookArr['amount'];
		    
		    $author = $book->getAuthorsAsString();
			$authorIds = $book->getAuthorIds();
			
			$authorStr = $author . ' (';
			
			$authorStr .= $amount . ')';
			
			if($author != $previousAuthor):?>
				<tr class="author">
					<td>&nbsp;</td>
					<th colspan="3"><?php echo $this->linkTo($authorStr, '/bookshelf/book/list/author/' . implode(',', $authorIds) );?></th>
				</tr>
			<?php 
			$previousAuthor = $author;
			endif;
		
			if($book->isRead() != 1):
				$class = 'is_not_read';
				$r++;
			else:
				$class = $r++ % 2 == 0 ? 'odd' : 'even';
			endif;		
			
		?>
		<tr class="<?php echo $class;?>">
			<td><?php echo $i;?></td>
			<td><?php echo $this->linkTo($book->getTitle(), '/bookshelf/book/view/id/' . $book->getId() );?></td>
			<td><div id="rating-<?php echo $book->getId();?>"></div></td>
			
			<?php 
		    if($book->isRead() ):
			    $this->inlineScript()->captureStart(); ?>
			
				$('#rating-' + <?php echo $book->getId();?>).raty({
					start: <?php echo $book->getRating();?>,
					path: '/img/',
					click: rate,
					readOnly: <?php echo Munkirjat_Auth::isLoggedIn() ? 'false' : 'true';?>
				});
            <?php 
                $this->inlineScript()->captureEnd(); 
            endif;
            ?>
		</tr>
		<?php $i++; endforeach;?>
	</table>
<?php endif;?>