<?php echo $this->render('book/partials/init-rating2.phtml');?>

<h1><?php echo $this->escape('Rate a book');?></h1>

<div id="book">
    <?php echo $this->partial('book/partials/rate-book-table.phtml', array('book' => $this->book) );?>
</div>

<?php $this->inlineScript()->captureStart(); ?>
$(function() {
    $('td.control a#delete').bind('click', function()
    {
    	return confirm('Do you really want to remove this book?');
    });
});
<?php $this->inlineScript()->captureEnd(); ?>