SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ;

USE `mydb`;

ALTER TABLE `munkirjat_db`.`book` ADD COLUMN `language_id` INT(10) UNSIGNED NULL DEFAULT NULL  AFTER `title` , ADD COLUMN `page_count` INT(5) UNSIGNED NULL DEFAULT NULL  AFTER `language_id` , ADD COLUMN `is_read` TINYINT(1) UNSIGNED NULL DEFAULT 0  AFTER `page_count` , ADD COLUMN `started_reading` DATETIME NULL DEFAULT NULL  AFTER `is_read` , ADD COLUMN `finished_reading` DATETIME NULL DEFAULT NULL  AFTER `started_reading` , ADD COLUMN `created` DATETIME NULL DEFAULT NULL  AFTER `finished_reading` , ADD COLUMN `updated` DATETIME NULL DEFAULT NULL  AFTER `created` , ADD COLUMN `isbn` VARCHAR(13) NULL DEFAULT NULL  AFTER `updated` ;

CREATE  TABLE IF NOT EXISTS `munkirjat_db`.`genre` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT ,
  `name` VARCHAR(45) NOT NULL ,
  PRIMARY KEY (`id`) ,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_swedish_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
