SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

CREATE  TABLE IF NOT EXISTS `munkirjat_db`.`book_author` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT ,
  `book_id` INT(10) UNSIGNED NULL DEFAULT NULL ,
  `author_id` INT(10) UNSIGNED NULL DEFAULT NULL ,
  PRIMARY KEY (`id`) ,
  UNIQUE INDEX `index2` (`book_id` ASC, `author_id` ASC) ,
  INDEX `fk_ba_book` (`book_id` ASC) ,
  INDEX `fk_ba_author` (`author_id` ASC) ,
  CONSTRAINT `fk_ba_book`
    FOREIGN KEY (`book_id` )
    REFERENCES `munkirjat_db`.`book` (`id` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ba_author`
    FOREIGN KEY (`author_id` )
    REFERENCES `munkirjat_db`.`author` (`id` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_swedish_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
