<?php $this->inlineScript()->captureStart(); ?>
$(function() {
    Munkirjat.account.initialize({
        usernameAvailableAction: '<?php echo $this->url(array(
                         'module' => 'user',
                         'controller' => 'account',
                         'action' => 'username-available',
                         'format' => 'json',
                       ), 'default', true); ?>',
                   
        emailAvailableAction: '<?php echo $this->url(array(
                         'module' => 'user',
                         'controller' => 'account',
                         'action' => 'email-available',
                         'format' => 'json',
                       ), 'default', true); ?>'                       
    });
});
<?php $this->inlineScript()->captureEnd(); ?>