<?php

/**
 * Default Layout
 *  
 * @author
 * @version
 */
echo '<?xml version="1.0" encoding="UTF-8" ?>';
echo $this->doctype() 
?>

<html>

	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<?php 
		
		//$this->headLink()->appendStylesheet($this->baseUrl('/assets/css/1140.css') );
		//$this->headLink()->appendStylesheet($this->baseUrl('/assets/css/style.css') );
		
		echo $this->headTitle();
		
		echo $this->headLink();
		
		echo $this->jQuery();
        
        
        $jsFile = $this->assetic(ROOT . '/public/assets/assetic/js/main.js', '/assets/assetic/js/main.js?v=2')->addJsFiles(array(
            ROOT . '/public/assets/js/munkirjat.js',
            ROOT . '/public/assets/js/user/account.js',
            ROOT . '/public/assets/js/jquery.ui.sortable.js',
            ROOT . '/public/assets/js/jquery.ui.draggable.js',
            ROOT . '/public/assets/js/bsmselect.js',
            ROOT . '/public/assets/js/bsmselect.sortable.js',
            ROOT . '/public/assets/js/bsmselect.compatibility.js',
            ROOT . '/public/assets/js/Jme/selector.js',
            ROOT . '/public/assets/js/bookshelf/author.js',
            ROOT . '/public/assets/js/bookshelf/bookshelf.js',
            ROOT . '/public/assets/js/jquery.raty-1.4.0/js/jquery.raty.min.js',
        ))->dumpJs();    
        
        
        $cssFile = $this->assetic(ROOT . '/public/assets/assetic/css/main.css', '/assets/assetic/css/main.css?v=2')->addCssFiles(array(
            ROOT . '/public/assets/css/1140.css',
            ROOT . '/public/assets/css/style.css',
            ROOT . '/public/assets/css/bsmselect.css',
        ))->dumpCss();
        
        $this->inlineScript()->offsetSetFile(-100, $jsFile);
        
	    echo $this->headScript();
	    ?>
        <link href="<?php echo $cssFile;?>" media="screen" rel="stylesheet" type="text/css" />
        <?php
        echo $this->headStyle();
	    ?>

	</head>
	
	<body>
		
		<div id="nav">
			<?php echo $this->navigation()->menu()->render(); ?>
		</div>
		<div id="container">
    		<div id="sidebar_left" class="sidebar">
    			<?php 
                
                                                
                if(!($html = $this->cache('content')->load('sidebar_left') ) ):
                    $html = $this->partial('partials/leftpanel.phtml');
                    
                    $this->cache('content')->save($html);
                endif;
                
                echo $html;?>

    		</div>			
    		
    		<div id="main">	
    			<?php 
    			if(isset($this->messages) ):
    				foreach ($this->messages as $message): ?>
    			        <div class="message"><div class="ui-widget">
    						<div class="ui-state-highlight highlight ui-corner-all"> 
    							<p>
    			                    <span class="ui-icon ui-icon-close"></span>
    			                    <span class="ui-icon ui-icon-info"></span>
    			                    <?php echo $message; ?>
    			                </p>
    						</div>
    					</div></div>
    			<?php endforeach; 
    			endif;
    			?>
    			
    			<?php echo $this->layout()->content ?>
    	
    		</div>
    		
    		<div class="sidebar" id="sidebar_right">
    			<?php 
    			
    			if(!($html = $this->cache('content')->load('sidebar_right') ) ):
    				$html = $this->partial('partials/rightpanel.phtml');
    				
    				$this->cache('content')->save($html);
    			endif;
    			
    			echo $html;
    			?>
    		</div>
		</div>
		
		<script type="text/javascript" src="https://www.google.com/jsapi"></script>
		
		<?php echo $this->inlineScript();?>
	</body>

</html>
