SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ;

USE `mydb`;

ALTER TABLE `munkirjat_db`.`accountverification` ADD COLUMN `verification_date` DATETIME NULL DEFAULT NULL  AFTER `user_id` , ADD COLUMN `verified` TINYINT(1) UNSIGNED NULL DEFAULT NULL  AFTER `verification_date` 
, ADD INDEX `index4` (`verification_date` ASC) 
, ADD INDEX `index5` (`verified` ASC) ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
